---
- name: installing packages
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum: 
      name: httpd
      state: installed
    notify: start apache

  handlers: 
  - name: start apache
    service:
      name: httpd
      state: started    
